
// This file is automatically generated. DO NOT EDIT, all your changes would be lost.

//
//  PacketNgHelperEventSink.h
//  Pods
//
//  Created by 汪洋 on 2023/2/27.
//

#import <Foundation/Foundation.h>
#import <Flutter/Flutter.h>

@interface PacketNgHelperEventSink : NSObject <FlutterStreamHandler>

@property (nonatomic, copy) FlutterEventSink event;

@end
