name: packet_ng_helper
description: packet_ng for Flutter.
version: 0.0.2
homepage: https://github.com/WangYng
repository: https://github.com/WangYng/packet_ng_helper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: io.github.wangyng.packet_ng_helper
        pluginClass: PacketNgHelperPlugin
      ios:
        pluginClass: PacketNgHelperPlugin
