
// This file is automatically generated. DO NOT EDIT, all your changes would be lost.

package io.github.wangyng.packet_ng_helper;

import io.flutter.plugin.common.EventChannel;

public class PacketNgHelperEventSink {
    EventChannel.EventSink event;
}
